[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B4D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
